- name: WebServer in 308
  hosts: "{{Group}}"
  become: true

  vars:
    packages_stage_1:
      - git
      - wget
      - curl
      - sudo
      - fontconfig
      - openjdk-17-jre
      - ca-certificates
    packages_stage_2:
      - jenkins
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:

  - name: Update packets library
    ansible.builtin.apt:
      update_cache: true

  - name: Upgrade installed packages
    ansible.builtin.apt:
      upgrade: true
  
  - name: Install started packages
    ansible.builtin.apt:
      name: "{{ packages_stage_1 }}"
      state: latest

  - name: Download Jenkins key
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc

  - name: Add Jenkins repository to sources.list
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/jenkins.list
      line: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
      create: true

  - name: Create directory for apt keyrings
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Change permissions for Docker GPG key
    ansible.builtin.file:
      path: /etc/apt/keyrings/docker.asc
      mode: '0644'  

  - name: Add Docker repository to sources.list
    ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] 
          zhttps://download.docker.com/linux/debian $(. /etc/os-release && echo "bookworm") 
          stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update packets library 
    ansible.builtin.apt:
      update_cache: true

  - name: Update System
    ansible.builtin.apt:
      upgrade: true

  - name: Install final packages
    ansible.builtin.apt:
      name: "{{ packages_stage_2 }}"
      state: latest

  - name: Add user to docker group
    ansible.builtin.user:
      name: cisco
      groups: docker
      append: true

  - name: Start jenkins.service
    ansible.builtin.service:
      name: jenkins
      state: started
      enabled: true

  - name: Start docker.service
    ansible.builtin.service:
      name: docker
      state: started
      enabled: true

  - name: Read Jenkins Secret Key
    ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: file_contents
    changed_when: false

  - name: Print Jenkins Secret Key
    ansible.builtin.debug:
      msg: "{{ file_contents.stdout }}"